### ISSUE TITLE
Alguns problemas

### ISSUE THREAD

**Issue by Takasakiii** [Yummiii/Neptune#1]
- Caminhos poderiam ser relativos, podendo usar a lib `dirs` para obter a pasta de usuário
 - Poderia ter um jeito de easy colocar na inicialização do sistema
 - Modo de usar uma hotkey para pessoas que não possuem Arduíno
 - Poderia juntar a parte de invocar as telas com o rust

**Comment by Takasakiii** [comment]
:heart:

**Comment by Yummiii** [comment]
fixed :+1:
